import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@components/UI/navbar/page";
import Footer from "@components/UI/footer/page";
import Notification from "@components/UI/notification/page";
import { SessionProvider } from "next-auth/react";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={jakarta.className}>
          <Navbar cartItemsCount={0} />
          {children}
          <Notification />
          <Footer />
        </body>
      </html>
    </SessionProvider>
  );
}
