import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "@app/globals.css";
import Footer from "@components/UI/footer/footer";
import { SessionProvider } from "next-auth/react";
import Navbar from "@components/UI/navbar/navbar";

const work_sans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={`${work_sans.className} m-0 p-0`}>{children}</body>
      </html>
    </SessionProvider>
  );
}
